import createHttpError from 'http-errors';
import { getAllContacts, getContactById } from '../services/contacts.js';
export const getAllContactsController = async (req, res,next) => {
     const contacts = await getAllContacts();

    res.status(200).json({
       status: 200,
       message: 'Successfully found contacts!',
       data: contacts,
     });
   };
   export const getContactByIdController = async (req, res) => {
     const { contactId } = req.params;
     const contact = await getContactById(contactId);

     if (contact == null) {
       throw createHttpError(404, 'Contact not found');
  
     }

     res.status(200).json({
       status: 200,
       message: `Successfully found contact with id ${contactId}!`,
       data: contact,
     });
   };